name: Telegram Scheduled Sender

on:
  workflow_dispatch: {}  # cron-job.org هر ۱۶ دقیقه این رو صدا میزنه (دقیق و سر وقت)

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install telethon

      - name: Send message
        env:
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send.py
